import React from "react";
import "./ReportsSection.css";

export default function ReportsSection({ currentLocation, data, reliabilityData, userRole }) {
  if (!currentLocation && !data) return null;

  const handlePrint = () => {
    window.print();
  };

  const summary = data?.summary || {};
  const peakProb = summary.peak_bust_probability !== undefined 
    ? `${(summary.peak_bust_probability * 100).toFixed(1)}%` 
    : "Not available";
  
  const riskLevel = summary.overall_risk_level || "Not available";
  const peakTime = summary.peak_probability_timestamp 
    ? new Date(summary.peak_probability_timestamp).toLocaleString() 
    : "Not available";
  
  const horizon = summary.total_hourly_predictions 
    ? `${Math.round(summary.total_hourly_predictions / 24)} days / ${summary.total_hourly_predictions} hourly predictions` 
    : "Not available";

  const verificationStatus = reliabilityData?.status === "insufficient_data" 
    ? "Collecting data (insufficient historical pairs)" 
    : reliabilityData?.status || "Not available";

  const formatRole = (role) => {
    if (!role) return "Authorized Personnel";
    const titles = {
      "meteorologist": "Meteorologist / Weather Forecaster",
      "disaster_management": "Disaster Management Authority",
      "government": "Government / Administration",
      "operational": "Operational Weather Team",
      "researcher": "Weather Researcher"
    };
    return titles[role] || role;
  };

  return (
    <div className="card reports-card">
      <div className="card-body">
        <div className="reports-header">
          <div>
            <div className="section-heading" style={{ marginBottom: "4px" }}>
              <span className="icon" aria-hidden="true">📑</span>
              Operational forecast-bust analysis and risk summary
            </div>
            <p className="text-muted" style={{ fontSize: "0.85rem", margin: 0 }}>
              Generated for: {currentLocation?.name || "Unknown Location"}
            </p>
          </div>
          <button className="btn-print" onClick={handlePrint}>
            🖨️ Print / Save Report
          </button>
        </div>

        <div className="reports-grid">
          <div className="report-item">
            <div className="report-label">Selected Location</div>
            <div className="report-value">{currentLocation?.name || "Not available"}</div>
          </div>
          <div className="report-item">
            <div className="report-label">Overall Bust Risk</div>
            <div className={`report-value risk-badge risk-${riskLevel.toLowerCase()}`}>
              {riskLevel.toUpperCase()}
            </div>
          </div>
          <div className="report-item">
            <div className="report-label">Peak Bust Probability</div>
            <div className="report-value">{peakProb}</div>
          </div>
          <div className="report-item">
            <div className="report-label">Peak Risk Time</div>
            <div className="report-value">{peakTime}</div>
          </div>
          <div className="report-item">
            <div className="report-label">Model Version</div>
            <div className="report-value">SIH-79-MVP-v2</div>
          </div>
          <div className="report-item">
            <div className="report-label">Location Forecast Horizon</div>
            <div className="report-value">{horizon}</div>
          </div>
          <div className="report-item">
            <div className="report-label">Selected Regional Risk Day</div>
            <div className="report-value">Not available</div>
          </div>
          <div className="report-item">
            <div className="report-label">Verification Status</div>
            <div className="report-value">{verificationStatus}</div>
          </div>
        </div>

        <div className="reports-footer">
          Report generated by: <strong>{formatRole(userRole)}</strong>
        </div>
      </div>
    </div>
  );
}
